name: First CICD
on: 
  push:
    branches:
      - main1
  pull_request:
    branches:
      - main1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

    #check python, java, node mvn, npm version
      - name: Check Python version
        run: python --version
    # pip version
      - name: Check pip version
        run: pip --version


      - name: Check Java version
        run: java -version

      - name: Check Node.js version
        run: node --version

      - name: Check Maven version
        run: mvn --version

      - name: Check NPM version
        run: npm --version

